import { NextResponse } from 'next/server';
import { isStaff } from '@/lib/trainer/auth';
import { listPodcastProfiles, readPodcastProfile, writePodcastProfileAtomic } from '@/lib/podcast-title/store';
import { createProfileFromRequest, profileSummary, validId, type AdminPodcastProfile } from '@/lib/podcast-title/adminApi';
export const runtime = 'nodejs'; export const dynamic = 'force-dynamic';
const unauthorized = () => NextResponse.json({ error: 'unauthorized' }, { status: 401 });
export async function GET() { if (!await isStaff()) return unauthorized(); try { const ids = await listPodcastProfiles(); const profiles = (await Promise.all(ids.map(id => readPodcastProfile(id)))).filter((profile): profile is AdminPodcastProfile => Boolean(profile)).map(profileSummary); return NextResponse.json({ profiles }); } catch { return NextResponse.json({ error: 'storage_unavailable' }, { status: 500 }); } }
async function save(request: Request, update: boolean) { if (!await isStaff()) return unauthorized(); let payload: unknown; try { payload = await request.json(); } catch { return NextResponse.json({ error: 'invalid_json' }, { status: 400 }); } const id = payload && typeof payload === 'object' ? (payload as { id?: unknown }).id : undefined; if (typeof id !== 'string' || !validId(id)) return NextResponse.json({ error: 'invalid_profile' }, { status: 400 }); try { const existing = await readPodcastProfile(id) as AdminPodcastProfile | null; if (update && !existing) return NextResponse.json({ error: 'profile_not_found' }, { status: 404 }); if (!update && existing) return NextResponse.json({ error: 'profile_exists' }, { status: 400 }); const profile = createProfileFromRequest(payload, existing ?? undefined); if (!profile) return NextResponse.json({ error: 'invalid_profile' }, { status: 400 }); if (!await writePodcastProfileAtomic(profile)) return NextResponse.json({ error: 'storage_unavailable' }, { status: 500 }); return NextResponse.json({ profile: profileSummary(profile) }, { status: update ? 200 : 201 }); } catch { return NextResponse.json({ error: 'storage_unavailable' }, { status: 500 }); } }
export async function POST(request: Request) { return save(request, false); }
export async function PUT(request: Request) { return save(request, true); }
