import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import test from 'node:test';

const root = path.resolve(process.cwd());
const script = path.join(root, 'scripts', 'compare-site-bot-architectures.mjs');

function directoryState(relativePath: string): { exists: boolean; names: string[]; mtimeMs?: number } {
  const absolutePath = path.join(root, relativePath);
  if (!fs.existsSync(absolutePath)) return { exists: false, names: [] };
  const stat = fs.statSync(absolutePath);
  return { exists: true, names: fs.readdirSync(absolutePath).sort(), mtimeMs: stat.mtimeMs };
}

test('cohort comparison report is deterministic, fixture-only, and leaves production data directories untouched', () => {
  const before = {
    clients: directoryState('data/clients'),
    sites: directoryState('data/sites'),
  };

  const actual = execFileSync(process.execPath, [script], { cwd: root, encoding: 'utf8' });

  assert.equal(actual, `# Research-first architecture cohort validation

All providers are mocked. Fixture input is ASCII-only. No production data directories are read or written.

## field
- legacy count: 6
- selected: home, services, alpha, beta, gamma, north
- backlog: none
- rejected: south: assertable local evidence is not established
- held: none
- clusters: alpha repair, beta repair, gamma repair, fixture expansion
- provenance: dataforseo/seed/fixture-seed, dataforseo/metrics/fixture-metrics, dataforseo/intent/fixture-intent, dataforseo/serp/fixture-serp
- gates: none
- link reachability: pass
- calls/cost: 4/$0.07
- FAQ decision: not generated by architecture comparison
- readiness: architecture_ready

## fixed
- legacy count: 6
- selected: home, services, alpha, beta, gamma
- backlog: none
- rejected: duplicate: cannibalization risk is too high
- held: uncertain: fixture ambiguity
- clusters: studio alpha, studio beta, studio gamma, fixture expansion
- provenance: dataforseo/seed/fixture-seed, dataforseo/metrics/fixture-metrics, dataforseo/intent/fixture-intent, dataforseo/serp/fixture-serp
- gates: gate-c-ambiguous: Ambiguous candidate evidence requires human review.
- link reachability: pass
- calls/cost: 4/$0.07
- FAQ decision: not generated by architecture comparison
- readiness: architecture_ready

## hybrid
- legacy count: 8
- selected: home, services, alpha, beta
- backlog: gamma, west, river
- rejected: none
- held: none
- clusters: event alpha, event beta, event gamma, fixture expansion
- provenance: dataforseo/seed/fixture-seed, dataforseo/metrics/fixture-metrics, dataforseo/intent/fixture-intent, dataforseo/serp/fixture-serp
- gates: none
- link reachability: pass
- calls/cost: 4/$0.07
- FAQ decision: not generated by architecture comparison
- readiness: architecture_ready
`);
  assert.deepEqual({ clients: directoryState('data/clients'), sites: directoryState('data/sites') }, before);
});

test('cohort comparison rejects non-fixture input', () => {
  assert.throws(() => execFileSync(process.execPath, [script, '--fixture', '../data'], { cwd: root, encoding: 'utf8', stdio: 'pipe' }));
});
