'use client';
import { useState } from 'react';
import { uiCopy } from '@/lib/podcast-title/uiCopy';
import type { AdminPodcastProfile, EpisodeSummary } from '@/lib/podcast-title/adminApi';
import type { StoredEpisodeAnalysis } from '@/lib/podcast-title/types';
import { ProfileEditor } from './ProfileEditor'; import { EpisodeForm } from './EpisodeForm'; import { AnalysisProgress } from './AnalysisProgress'; import { ResultPanel } from './ResultPanel'; import { HistoryPanel } from './HistoryPanel';
export function PodcastTitleWorkspace({ initialProfiles, initialEpisodes, fixtureRecord, fixtureRecords }: { initialProfiles: AdminPodcastProfile[]; initialEpisodes: EpisodeSummary[]; fixtureRecord?: StoredEpisodeAnalysis; fixtureRecords?: StoredEpisodeAnalysis[] }) { const [profiles, setProfiles] = useState(initialProfiles); const [selectedId, setSelectedId] = useState(initialProfiles[0]?.id ?? ''); const [episodes, setEpisodes] = useState(initialEpisodes); const [record, setRecord] = useState<StoredEpisodeAnalysis | undefined>(fixtureRecord); const [editing, setEditing] = useState(false); const [running, setRunning] = useState(false); const [error, setError] = useState(false); const profile = profiles.find(item => item.id === selectedId);
 async function refresh(profileId = selectedId) { if (!profileId) return; const response = await fetch(`/api/admin/podcast-titles/episodes?profileId=${encodeURIComponent(profileId)}`); if (!response.ok) { setError(true); return; } setEpisodes((await response.json()).episodes); setError(false); }
 async function analyze(input: Record<string, unknown>) { if (!selectedId || running) return; setRunning(true); setError(false); try { const response = await fetch('/api/admin/podcast-titles/analyze', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ ...input, profileId: selectedId }) }); if (!response.ok) throw new Error('failed'); setRecord((await response.json()).analysis); await refresh(); } catch { setError(true); } finally { setRunning(false); } }
 async function selectEpisode(episodeId: string) { if (!selectedId) return; try { const response = await fetch(`/api/admin/podcast-titles/episodes?profileId=${encodeURIComponent(selectedId)}&episodeId=${encodeURIComponent(episodeId)}`); if (!response.ok) throw new Error('failed'); setRecord((await response.json()).episode); } catch { setError(true); } }
 return <main dir="rtl" className="min-h-screen bg-[var(--bg)] px-4 py-6 text-[var(--text)]"><div className="mx-auto max-w-6xl space-y-5"><header className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-black">{uiCopy.appTitle}</h1><p className="text-sm text-[var(--muted)]">{uiCopy.appSubtitle}</p></div><div className="flex gap-2"><select value={selectedId} onChange={event => { setSelectedId(event.target.value); void refresh(event.target.value); }} className="min-h-[44px] rounded border border-[var(--border)] bg-[var(--surface)] px-3"><option value="">{uiCopy.profileLabel}</option>{profiles.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select><button type="button" onClick={() => setEditing(true)} className="min-h-[44px] rounded border border-[var(--border)] px-3">{profile ? uiCopy.editProfile : uiCopy.newProfile}</button></div></header>{error && <p aria-live="polite" className="text-red-400">{uiCopy.genericError}</p>}<div className="grid gap-5 md:grid-cols-2"><div className="md:order-2"><EpisodeForm profile={profile} disabled={!profile || running} onSubmit={analyze}/></div><div className="md:order-1"><HistoryPanel episodes={episodes} loading={running} error={error} onSelect={selectEpisode}/></div></div><AnalysisProgress active={running}/>{fixtureRecords ? fixtureRecords.map(item => <ResultPanel key={item.episodeId} record={item}/>) : <ResultPanel record={record}/>}{editing && <ProfileEditor profile={profile} onClose={() => setEditing(false)} onSaved={saved => { setProfiles(items => { const exists = items.some(item => item.id === saved.id); return exists ? items.map(item => item.id === saved.id ? saved : item) : [...items, saved]; }); setSelectedId(saved.id); }}/>}</div></main>; }
