'use client';
import { useEffect, useRef, useState } from 'react';
import { uiCopy } from '@/lib/podcast-title/uiCopy';
import { toArray, type AdminPodcastProfile } from '@/lib/podcast-title/adminApi';

export function ProfileEditor({ profile, onClose, onSaved }: { profile?: AdminPodcastProfile; onClose: () => void; onSaved: (profile: AdminPodcastProfile) => void }) {
  const dialog = useRef<HTMLDialogElement>(null); const [error, setError] = useState(false);
  useEffect(() => { const node = dialog.current; node?.showModal(); return () => node?.close(); }, []);
  async function save(form: HTMLFormElement) {
    const values = Object.fromEntries(new FormData(form));
    const body = { ...values, brandPhrases: toArray(String(values.brandPhrases ?? '')), topicScope: toArray(String(values.topicScope ?? '')), benefitTitlePreference: values.benefitTitlePreference === 'on', titleLimit: Number(values.titleLimit), descriptionLimit: Number(values.descriptionLimit) };
    const response = await fetch('/api/admin/podcast-titles/profiles', { method: profile ? 'PUT' : 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) });
    if (!response.ok) { setError(true); return; } onSaved((await response.json()).profile); onClose();
  }
  const value = (key: keyof AdminPodcastProfile) => profile?.[key] ?? '';
  return <dialog ref={dialog} onClose={onClose} className="w-[min(44rem,calc(100vw-2rem))] rounded-xl border border-[var(--border)] bg-[var(--surface)] p-0 text-[var(--text)] backdrop:bg-black/70"><form onSubmit={event => { event.preventDefault(); void save(event.currentTarget); }} className="space-y-3 p-5" dir="rtl"><div className="flex items-center justify-between"><h2 className="font-bold">{profile ? uiCopy.editProfile : uiCopy.newProfile}</h2><button type="button" onClick={onClose} className="min-h-[44px] px-3">{uiCopy.cancel}</button></div>{error && <p aria-live="polite" className="text-red-400">{uiCopy.genericError}</p>}<div className="grid gap-3 sm:grid-cols-2">{(['id','name','podcastName','targetAudience','podcastDomain','writingStyle','targetCountry','targetLanguage','titleLimit','descriptionLimit'] as const).map(key => <label key={key} className="text-sm"><span>{key === 'name' ? uiCopy.profileName : key === 'podcastName' ? uiCopy.podcastName : key === 'targetAudience' ? uiCopy.targetAudience : key === 'podcastDomain' ? uiCopy.podcastDomain : key === 'writingStyle' ? uiCopy.writingStyle : key === 'targetCountry' ? uiCopy.targetCountry : key === 'targetLanguage' ? uiCopy.targetLanguage : key === 'titleLimit' ? uiCopy.titleLimit : key === 'descriptionLimit' ? uiCopy.descriptionLimit : uiCopy.episodeId}</span><input name={key} required type={key.includes('Limit') ? 'number' : 'text'} readOnly={key === 'id' && Boolean(profile)} defaultValue={String(value(key))} className="mt-1 w-full rounded border border-[var(--border)] bg-[var(--elevated)] p-2" /></label>)}</div><label className="block text-sm">{uiCopy.brandPhrases}<textarea name="brandPhrases" defaultValue={(profile?.brandPhrases ?? []).join(', ')} className="mt-1 w-full rounded border border-[var(--border)] bg-[var(--elevated)] p-2" /></label><label className="block text-sm">{uiCopy.topicScope}<textarea name="topicScope" required defaultValue={(profile?.topicScope ?? []).join(', ')} className="mt-1 w-full rounded border border-[var(--border)] bg-[var(--elevated)] p-2" /></label><label className="flex min-h-[44px] items-center gap-2 text-sm"><input name="benefitTitlePreference" type="checkbox" defaultChecked={Boolean(value('benefitTitlePreference'))} />{uiCopy.benefitTitlePreference}</label><button className="min-h-[44px] rounded bg-[var(--accent)] px-4 font-bold text-white">{uiCopy.saveSettings}</button></form></dialog>;
}
