import { cookies } from 'next/headers';
import { redirect } from 'next/navigation';
import { ADMIN_COOKIE_NAME, verifyAdminToken } from '@/lib/admin-auth';
import { listPodcastProfiles, listEpisodeAnalyses, readEpisodeAnalysis, readPodcastProfile } from '@/lib/podcast-title/store';
import { episodeSummary, profileSummary, type AdminPodcastProfile, type EpisodeSummary } from '@/lib/podcast-title/adminApi';
import { uiCopy } from '@/lib/podcast-title/uiCopy';
import { PodcastTitleWorkspace } from '@/components/admin/podcast-title/PodcastTitleWorkspace';
import type { ScoredKeyword, StoredEpisodeAnalysis } from '@/lib/podcast-title/types';
export const metadata = { robots: { index: false }, title: 'Podcast title workspace | WAO' };
export const dynamic = 'force-dynamic';
function fixture(): StoredEpisodeAnalysis { const theme = { format: 'mixed' as const, theme: uiCopy.primaryTheme, supportingTopics: [], examples: [], excludedTopics: [uiCopy.warnings], listenerIntent: uiCopy.listenerIntent, listenerPromise: uiCopy.appSubtitle, seeds: ['NLP'], confidence: 72 }; return { schemaVersion: 1, profileId: 'fixture-1', episodeId: 'fixture-review', input: { transcript: uiCopy.transcript, currentTitle: uiCopy.currentTitle, currentDescription: uiCopy.currentDescription }, transcriptDigest: 'fixture', theme, providerUsage: [], createdAt: '2026-01-01T00:00:00.000Z', updatedAt: '2026-01-01T00:00:00.000Z', result: { decision: 'HUMAN_REVIEW', reason: 'fixture', theme, keywordEvidence: [], titles: [{ role: 'balanced', title: uiCopy.recommendedTitle, primaryPhrase: 'NLP' }, { role: 'search_focused', title: uiCopy.alternativeTitles, primaryPhrase: 'NLP' }, { role: 'curiosity', title: uiCopy.useTitle, primaryPhrase: 'NLP' }], description: uiCopy.shortDescription, currentTitleScore: 42, recommendedTitleScore: 72, fallbackUsed: true, llmCallsUsed: 0 } }; }
function fixtures(): StoredEpisodeAnalysis[] { const review = fixture(); const positiveEvidence: ScoredKeyword = { phrase: 'podcast planning', searchVolume: 100, monthlySearches: [], source: 'keyword_ideas', taskIds: ['fixture-task'], providerCostUsd: 0, components: { themeRelevance: 90, intentMatch: 90, normalizedVolume: 100, titleNaturalness: 90, clickPotential: 90 }, score: 91.5, relevant: true }; const normal: StoredEpisodeAnalysis = { ...review, episodeId: 'fixture-normal', result: { ...review.result, decision: 'CHANGE', fallbackUsed: false, selectedKeyword: positiveEvidence, keywordEvidence: [positiveEvidence] } }; const fallback: StoredEpisodeAnalysis = { ...review, episodeId: 'fixture-fallback', result: { ...normal.result, fallbackUsed: true } }; return [normal, fallback, review]; }
async function loadInitial(): Promise<{ profiles: AdminPodcastProfile[]; episodes: EpisodeSummary[] }> { const ids = await listPodcastProfiles(); const profiles = (await Promise.all(ids.map(id => readPodcastProfile(id)))).filter((profile): profile is AdminPodcastProfile => Boolean(profile)); const selected = profiles[0]; if (!selected) return { profiles, episodes: [] }; const episodeIds = await listEpisodeAnalyses(selected.id); const episodes = (await Promise.all(episodeIds.slice(-20).map(id => readEpisodeAnalysis(selected.id, id)))).filter((record): record is StoredEpisodeAnalysis => Boolean(record)).sort((a, b) => b.createdAt.localeCompare(a.createdAt)).map(episodeSummary); return { profiles, episodes }; }
export default async function PodcastTitlesPage({ searchParams }: { searchParams: Promise<{ fixture?: string }> }) { const jar = await cookies(); if (!await verifyAdminToken(jar.get(ADMIN_COOKIE_NAME)?.value ?? '')) redirect('/admin/login?next=%2Fadmin%2Fpodcast-titles'); const params = await searchParams; if (process.env.NODE_ENV !== 'production' && params.fixture === '1') { const records = fixtures(); const profile: AdminPodcastProfile = { id: 'fixture-1', name: uiCopy.profileLabel, audience: uiCopy.targetAudience, titleMinLength: 10, titleMaxLength: 80, descriptionMinLength: 20, descriptionMaxLength: 160, seedKeywords: ['NLP'], podcastName: uiCopy.podcastName, targetAudience: uiCopy.targetAudience, podcastDomain: uiCopy.podcastDomain, writingStyle: uiCopy.writingStyle, brandPhrases: [uiCopy.brandPhrases], topicScope: ['NLP'], benefitTitlePreference: true, targetCountry: 'IL', targetLanguage: 'he', titleLimit: 80, descriptionLimit: 160 }; return <PodcastTitleWorkspace initialProfiles={[profile]} initialEpisodes={records.map(episodeSummary)} fixtureRecord={records[0]} fixtureRecords={records}/>; } const initial = await loadInitial(); return <PodcastTitleWorkspace initialProfiles={initial.profiles.map(profile => ({ ...profile, ...profileSummary(profile) }))} initialEpisodes={initial.episodes}/>; }
