import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
const root = path.resolve(process.cwd());
const read = file => fs.readFileSync(path.join(root, file), 'utf8');
test('podcast admin gates precede storage and provider access', () => {
  for (const file of ['src/app/api/admin/podcast-titles/profiles/route.ts', 'src/app/api/admin/podcast-titles/analyze/route.ts', 'src/app/api/admin/podcast-titles/episodes/route.ts']) {
    const source = read(file); assert.ok(source.indexOf('isStaff') < source.indexOf('request.json') || !source.includes('request.json')); assert.ok(source.includes("error: 'unauthorized'"));
  }
});
test('proxy and page protect the workspace', () => { const proxy = read('src/proxy.ts'); const page = read('src/app/(product)/admin/podcast-titles/page.tsx'); assert.ok(proxy.includes("'/admin/podcast-titles'")); assert.ok(proxy.includes("'/admin/podcast-titles/:path*'")); assert.ok(page.indexOf('verifyAdminToken') < page.indexOf('loadInitial')); });
test('copy and visual fixture contracts remain isolated', () => { const files = ['src/lib/podcast-title/uiCopy.ts', 'src/components/admin/podcast-title/PodcastTitleWorkspace.tsx', 'src/components/admin/podcast-title/ProfileEditor.tsx', 'src/components/admin/podcast-title/EpisodeForm.tsx', 'src/components/admin/podcast-title/AnalysisProgress.tsx', 'src/components/admin/podcast-title/ResultPanel.tsx', 'src/components/admin/podcast-title/HistoryPanel.tsx']; for (const file of files) assert.equal(/[\u0590-\u05ff]/.test(read(file)), false); const page = read('src/app/(product)/admin/podcast-titles/page.tsx'); assert.ok(page.includes("process.env.NODE_ENV !== 'production'")); assert.ok(page.indexOf('verifyAdminToken') < page.indexOf("params.fixture === '1'")); const episodes = read('src/app/api/admin/podcast-titles/episodes/route.ts'); assert.ok(!episodes.includes('transcript')); });
test('episode form omits identifier from analysis requests', () => { const form = read('src/components/admin/podcast-title/EpisodeForm.tsx'); assert.equal(form.includes('name="episodeId"'), false); assert.equal(form.includes('uiCopy.episodeId'), false); assert.equal(form.includes('uiCopy.episodeIdHelp'), false); const workspace = read('src/components/admin/podcast-title/PodcastTitleWorkspace.tsx'); assert.ok(workspace.includes("fetch('/api/admin/podcast-titles/analyze'")); assert.ok(workspace.includes('JSON.stringify({ ...input, profileId: selectedId })')); });
test('completed review evidence and authenticated fixture contracts remain explicit', () => { const panel = read('src/components/admin/podcast-title/ResultPanel.tsx'); const page = read('src/app/(product)/admin/podcast-titles/page.tsx'); const verifier = read('scripts/verify-podcast-human-review-ui.mjs'); for (const id of ['podcast-decision', 'podcast-recommendation-evidence', 'podcast-selected-phrase', 'podcast-selected-volume', 'podcast-current-title-evidence', 'podcast-current-title-phrase', 'podcast-current-title-volume', 'podcast-title-suggestion-0', 'podcast-title-suggestion-1', 'podcast-title-suggestion-2']) assert.ok(panel.includes(id)); assert.ok(panel.includes('data-testid={`podcast-result-${record.episodeId}`}')); assert.ok(verifier.includes("const REVIEW_PANEL_TEST_ID = 'podcast-result-fixture-review';")); assert.ok(verifier.includes('const reviewPanel = await page.$(`[data-testid="${REVIEW_PANEL_TEST_ID}"]`);')); assert.ok(panel.includes('uiCopy.currentTitle')); assert.ok(panel.includes('uiCopy.recommendedTitle')); assert.ok(panel.includes('result.currentTitleKeywordEvidence')); assert.ok(panel.includes("evidence?.status === 'available'")); assert.ok(panel.includes('result.selectedKeyword')); assert.equal(panel.includes('result.failure ? uiCopy.genericError'), false); assert.ok(page.indexOf('verifyAdminToken') < page.indexOf("params.fixture === '1'")); assert.ok(page.includes("process.env.NODE_ENV !== 'production'")); assert.ok(page.includes("phrase: 'fixture recommended phrase'")); assert.ok(page.includes("phrase: 'fixture old title phrase'")); });
test('non-review results visibly bind exact positive keyword evidence', () => { const panel = read('src/components/admin/podcast-title/ResultPanel.tsx'); const page = read('src/app/(product)/admin/podcast-titles/page.tsx'); assert.ok(panel.includes('value={result.selectedKeyword?.phrase}')); assert.ok(panel.includes('value={result.selectedKeyword?.searchVolume}')); assert.ok(page.includes("const positiveEvidence: ScoredKeyword = { phrase: 'podcast planning', searchVolume: 100")); assert.ok(page.includes('relevant: true')); assert.ok(page.includes('selectedKeyword: positiveEvidence, keywordEvidence: [positiveEvidence]')); });
test('analyze route persists only completed outcomes and maps typed failures safely', () => { const route = read('src/app/api/admin/podcast-titles/analyze/route.ts'); assert.ok(route.includes('analyzePodcastEpisodeOutcome')); assert.ok(route.includes("outcome.status === 'completed'")); assert.ok(route.includes('writeEpisodeAnalysisAtomic')); assert.ok(route.includes("timeout: { status: 504, error: 'analysis_timeout' }")); assert.ok(route.includes("aborted: { status: 503, error: 'analysis_aborted' }")); assert.ok(route.includes("unavailable: { status: 502, error: 'provider_unavailable' }")); assert.ok(route.includes("invalid_output: { status: 502, error: 'provider_invalid_output' }")); assert.equal(route.includes('message.includes'), false); assert.equal(route.includes('result.failure'), false); });
test('episode APIs exclude legacy operational records while retaining completed reviews', () => { const api = read('src/lib/podcast-title/adminApi.ts'); const episodes = read('src/app/api/admin/podcast-titles/episodes/route.ts'); const page = read('src/app/(product)/admin/podcast-titles/page.tsx'); assert.ok(api.includes('isLegacyOperationalRecord')); assert.ok(api.includes('EpisodeSummary | null')); assert.ok(api.includes('return null')); assert.ok(episodes.includes("error: 'analysis_failed'")); assert.ok(episodes.includes('.map(episodeSummary).filter')); assert.ok(page.includes('.map(episodeSummary).filter')); });
test('podcast fixture output isolation is opt-in, child-only, and cleanup-guarded', () => { const config = read('next.config.ts'); const verifier = read('scripts/verify-podcast-human-review-ui.mjs'); assert.ok(config.includes('WAO_PODCAST_FIXTURE_DIST_DIR')); assert.ok(config.includes('/^\\.next-podcast-fixture-[A-Za-z0-9_-]{1,64}$/')); assert.ok(config.includes('distDir: podcastFixtureDistDir')); assert.ok(verifier.includes('const FIXTURE_DIST_DIR_PATTERN = /^\\.next-podcast-fixture-[A-Za-z0-9_-]{1,64}$/;')); assert.ok(verifier.includes('randomBytes')); assert.ok(verifier.includes('WAO_PODCAST_FIXTURE_DIST_DIR: fixtureDistDir')); assert.ok(verifier.includes('env: { ...process.env, WAO_PODCAST_FIXTURE_DIST_DIR: fixtureDistDir }')); assert.ok(verifier.includes('fixtureDistCreated = true')); assert.ok(verifier.includes("fail('FIXTURE_DIST_DIR_INVALID')")); assert.ok(verifier.includes("fail('FIXTURE_DIST_DIR_PATH_INVALID')")); assert.ok(verifier.includes('await fs.rm(fixtureDistPath, { recursive: true, force: false });')); assert.ok(verifier.includes('fixture_dist_cleanup=true')); });
