import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
const root = path.resolve(process.cwd());
const read = file => fs.readFileSync(path.join(root, file), 'utf8');
test('podcast admin gates precede storage and provider access', () => {
  for (const file of ['src/app/api/admin/podcast-titles/profiles/route.ts', 'src/app/api/admin/podcast-titles/analyze/route.ts', 'src/app/api/admin/podcast-titles/episodes/route.ts']) {
    const source = read(file); assert.ok(source.indexOf('isStaff') < source.indexOf('request.json') || !source.includes('request.json')); assert.ok(source.includes("error: 'unauthorized'"));
  }
});
test('proxy and page protect the workspace', () => { const proxy = read('src/proxy.ts'); const page = read('src/app/(product)/admin/podcast-titles/page.tsx'); assert.ok(proxy.includes("'/admin/podcast-titles'")); assert.ok(proxy.includes("'/admin/podcast-titles/:path*'")); assert.ok(page.indexOf('verifyAdminToken') < page.indexOf('loadInitial')); });
test('copy and visual fixture contracts remain isolated', () => { const files = ['src/lib/podcast-title/uiCopy.ts', 'src/components/admin/podcast-title/PodcastTitleWorkspace.tsx', 'src/components/admin/podcast-title/ProfileEditor.tsx', 'src/components/admin/podcast-title/EpisodeForm.tsx', 'src/components/admin/podcast-title/AnalysisProgress.tsx', 'src/components/admin/podcast-title/ResultPanel.tsx', 'src/components/admin/podcast-title/HistoryPanel.tsx']; for (const file of files) assert.equal(/[\u0590-\u05ff]/.test(read(file)), false); const page = read('src/app/(product)/admin/podcast-titles/page.tsx'); assert.ok(page.includes("process.env.NODE_ENV !== 'production'")); assert.ok(page.indexOf('verifyAdminToken') < page.indexOf("params.fixture === '1'")); const episodes = read('src/app/api/admin/podcast-titles/episodes/route.ts'); assert.ok(!episodes.includes('transcript')); });
test('episode form omits identifier from analysis requests', () => { const form = read('src/components/admin/podcast-title/EpisodeForm.tsx'); assert.equal(form.includes('name="episodeId"'), false); assert.equal(form.includes('uiCopy.episodeId'), false); assert.equal(form.includes('uiCopy.episodeIdHelp'), false); const workspace = read('src/components/admin/podcast-title/PodcastTitleWorkspace.tsx'); assert.ok(workspace.includes("fetch('/api/admin/podcast-titles/analyze'")); assert.ok(workspace.includes('JSON.stringify({ ...input, profileId: selectedId })')); });
test('result panel selects generic error only for operational reviews', () => { const panel = read('src/components/admin/podcast-title/ResultPanel.tsx'); assert.ok(panel.includes('result.failure ? uiCopy.genericError : uiCopy.lowConfidence')); });
test('non-review results visibly bind exact positive keyword evidence', () => { const panel = read('src/components/admin/podcast-title/ResultPanel.tsx'); const page = read('src/app/(product)/admin/podcast-titles/page.tsx'); assert.ok(panel.includes("Info label={uiCopy.selectedKeyword} value={result.selectedKeyword?.phrase ?? ''}")); assert.ok(panel.includes("Info label={uiCopy.searchVolume} value={result.selectedKeyword?.searchVolume ?? ''}")); assert.ok(page.includes("const positiveEvidence: ScoredKeyword = { phrase: 'podcast planning', searchVolume: 100")); assert.ok(page.includes('relevant: true')); assert.ok(page.includes('selectedKeyword: positiveEvidence, keywordEvidence: [positiveEvidence]')); });
