import type { KeywordCandidate, ProviderUsageEntry } from './types';
export interface PodcastDataForSeoOptions { fetch?: typeof globalThis.fetch; token?: string; baseUrl?: string; locationCode?: number; languageCode?: string; budget?: { calls: number }; signal?: AbortSignal; timeoutMs?: number; }
type Task = { id?: string; cost?: number; status_code?: number; status_message?: string; result?: Array<Record<string, unknown>> };
const records = (v: unknown): Record<string, unknown>[] => Array.isArray(v) ? v.filter(v => Boolean(v) && typeof v === 'object' && !Array.isArray(v)) as Record<string, unknown>[] : [];
const text = (v: unknown) => typeof v === 'string' && v.trim() ? v.trim() : undefined;
const number = (v: unknown) => typeof v === 'number' && Number.isFinite(v) ? v : undefined;
function usage(operation: string, tasks: Task[]): ProviderUsageEntry { return { operation, taskIds: tasks.flatMap(t => t.id ? [t.id] : []), costUsd: tasks.reduce((sum, t) => sum + (number(t.cost) ?? 0), 0) }; }
function requestSignal(options: PodcastDataForSeoOptions) { const timeoutMs = options.timeoutMs ?? 15_000; if (!Number.isFinite(timeoutMs) || timeoutMs <= 0) throw new Error('Invalid DataForSEO timeout'); return options.signal ? AbortSignal.any([options.signal, AbortSignal.timeout(timeoutMs)]) : AbortSignal.timeout(timeoutMs); }
async function post(operation: string, endpoint: string, body: unknown, options: PodcastDataForSeoOptions): Promise<{ tasks: Task[]; usage: ProviderUsageEntry }> { const signal = requestSignal(options); if (options.signal?.aborted) throw options.signal.reason ?? new Error('DataForSEO request aborted'); const budget = options.budget ?? { calls: 0 }; if (budget.calls >= 3) throw new Error('DataForSEO call ceiling reached'); const token = options.token ?? process.env.DATAFORSEO_TOKEN; if (!token) throw new Error('DATAFORSEO_TOKEN is required'); budget.calls += 1; const response = await (options.fetch ?? globalThis.fetch)(`${options.baseUrl ?? 'https://api.dataforseo.com/v3'}${endpoint}`, { method: 'POST', headers: { Authorization: `Basic ${token}`, 'Content-Type': 'application/json' }, body: JSON.stringify(body), signal }); if (!response.ok) throw new Error(`DataForSEO HTTP ${response.status}`); const payload = await response.json() as { tasks?: unknown }; if (!payload || !Array.isArray(payload.tasks) || !payload.tasks.length || !payload.tasks.every(task => Boolean(task) && typeof task === 'object' && !Array.isArray(task))) throw new Error('DataForSEO malformed response'); const tasks = payload.tasks as Task[]; if (tasks.some(t => (t.status_code ?? 20000) >= 40000)) throw new Error('DataForSEO task failed'); if (tasks.some(t => t.result !== undefined && !Array.isArray(t.result))) throw new Error('DataForSEO malformed response'); return { tasks, usage: usage(operation, tasks) }; }
const task = (options: PodcastDataForSeoOptions) => ({ location_code: options.locationCode ?? 2376, language_code: options.languageCode ?? 'he' });
function items(tasks: Task[]) { return tasks.flatMap(t => t.result ?? []).flatMap(r => records(r.items)); }
export async function fetchPodcastKeywordIdeas(seeds: string[], options: PodcastDataForSeoOptions = {}): Promise<{ candidates: KeywordCandidate[]; usage: ProviderUsageEntry }> { const clean = [...new Set(seeds.map(v => v.trim()).filter(Boolean))]; if (!clean.length || clean.length > 3) throw new Error('Expected 1-3 seeds'); const result = await post('keyword_ideas', '/dataforseo_labs/google/keyword_ideas/live', [{ keywords: clean, closely_variants: false, limit: 30, include_serp_info: false, include_clickstream_data: false, ...task(options) }], options); return { candidates: items(result.tasks).flatMap(item => { const info = (item.keyword_info ?? {}) as Record<string, unknown>; const phrase = text(item.keyword) ?? text(info.keyword); if (!phrase) return []; const monthlySearches = records(info.monthly_searches).flatMap(v => { const year = number(v.year), month = number(v.month), searchVolume = number(v.search_volume); return year === undefined || month === undefined || searchVolume === undefined ? [] : [{ year, month, searchVolume }]; }); return [{ phrase, searchVolume: number(info.search_volume) ?? null, monthlySearches, source: 'keyword_ideas' as const, taskIds: result.usage.taskIds, providerCostUsd: result.usage.costUsd }]; }), usage: result.usage }; }
export async function fetchPodcastAutocomplete(seed: string, options: PodcastDataForSeoOptions = {}): Promise<{ suggestions: string[]; usage: ProviderUsageEntry }> { if (!seed.trim()) throw new Error('Seed required'); const result = await post('autocomplete', '/serp/google/autocomplete/live/advanced', [{ keyword: seed, ...task(options) }], options); const suggestions = [...new Set(items(result.tasks).flatMap(v => [text(v.keyword), text(v.suggestion)]).filter((v): v is string => Boolean(v)))].slice(0, 10); return { suggestions, usage: result.usage }; }
export async function fetchPodcastSearchVolume(phrases: string[], options: PodcastDataForSeoOptions = {}): Promise<{ candidates: KeywordCandidate[]; usage: ProviderUsageEntry }> { const clean = [...new Set(phrases.map(v => v.trim()).filter(Boolean))]; if (!clean.length) throw new Error('Keywords required'); const result = await post('search_volume', '/keywords_data/google/search_volume/live', [{ keywords: clean, ...task(options) }], options); return { candidates: items(result.tasks).flatMap(item => { const phrase = text(item.keyword); if (!phrase) return []; const monthlySearches = records(item.monthly_searches).flatMap(v => { const year = number(v.year), month = number(v.month), searchVolume = number(v.search_volume); return year === undefined || month === undefined || searchVolume === undefined ? [] : [{ year, month, searchVolume }]; }); return [{ phrase, searchVolume: number(item.search_volume) ?? null, monthlySearches, source: 'search_volume' as const, taskIds: result.usage.taskIds, providerCostUsd: result.usage.costUsd }]; }), usage: result.usage }; }
