import type { EpisodeAnalysisInput, KeywordCandidate, PodcastProfile, ThemeAnalysis, WriterDraftOutput, WriterRankingOutput } from './types';
const ID = /^[A-Za-z0-9][A-Za-z0-9_-]{0,79}$/;
export const PODCAST_TITLE_MIN_LENGTH = 20;
export const PODCAST_TITLE_MAX_LENGTH = 100;
export const PODCAST_DESCRIPTION_MIN_LENGTH = 80;
export const PODCAST_DESCRIPTION_MAX_LENGTH = 1000;
const isRecord = (v: unknown): v is Record<string, unknown> => Boolean(v) && typeof v === 'object' && !Array.isArray(v);
const string = (v: unknown, min = 1, max = Infinity): v is string => typeof v === 'string' && v.length >= min && v.length <= max;
const nonBlank = (v: unknown): v is string => string(v) && v.trim().length > 0;
const score = (v: unknown): v is number => typeof v === 'number' && Number.isFinite(v) && v >= 0 && v <= 100;
export function validatePodcastProfile(value: unknown): value is PodcastProfile { if (!isRecord(value) || !nonBlank(value.id) || !ID.test(value.id) || !nonBlank(value.name) || !nonBlank(value.audience) || !Array.isArray(value.seedKeywords) || value.seedKeywords.length > 3 || new Set(value.seedKeywords.map(v => typeof v === 'string' ? v.trim().toLocaleLowerCase() : '')).size !== value.seedKeywords.length || !value.seedKeywords.every(nonBlank)) return false; return typeof value.titleMinLength === 'number' && typeof value.titleMaxLength === 'number' && value.titleMinLength >= PODCAST_TITLE_MIN_LENGTH && value.titleMaxLength <= PODCAST_TITLE_MAX_LENGTH && value.titleMinLength <= value.titleMaxLength && typeof value.descriptionMinLength === 'number' && typeof value.descriptionMaxLength === 'number' && value.descriptionMinLength >= PODCAST_DESCRIPTION_MIN_LENGTH && value.descriptionMaxLength <= PODCAST_DESCRIPTION_MAX_LENGTH && value.descriptionMinLength <= value.descriptionMaxLength; }
export function upgradeLegacyPodcastProfile(value: unknown): PodcastProfile | null { if (validatePodcastProfile(value)) return value; if (!isRecord(value) || value.titleMinLength !== 10 || value.descriptionMinLength !== 20) return null; const upgraded = { ...value, titleMinLength: PODCAST_TITLE_MIN_LENGTH, descriptionMinLength: PODCAST_DESCRIPTION_MIN_LENGTH }; return validatePodcastProfile(upgraded) ? upgraded : null; }
export function validateEpisodeInput(value: unknown): value is EpisodeAnalysisInput { if (!isRecord(value) || !string(value.transcript, 500, 300000)) return false; return (value.episodeId === undefined || value.episodeId === '' || (string(value.episodeId) && ID.test(value.episodeId))) && (value.currentTitle === undefined || string(value.currentTitle, 0, 200)) && (value.currentDescription === undefined || string(value.currentDescription, 0, 2000)); }
export function validateThemeAnalysis(value: unknown): value is ThemeAnalysis { if (!isRecord(value) || !['intro','single_topic','interview','personal_story','educational','case_study','mixed'].includes(String(value.format)) || !nonBlank(value.theme) || !nonBlank(value.listenerIntent) || !nonBlank(value.listenerPromise) || !score(value.confidence) || !Array.isArray(value.seeds) || value.seeds.length < 2 || value.seeds.length > 3 || new Set(value.seeds.map(v => typeof v === 'string' ? v.trim().toLocaleLowerCase() : '')).size !== value.seeds.length || !value.seeds.every(nonBlank)) return false; return ['supportingTopics','examples','excludedTopics'].every(k => Array.isArray(value[k]) && (value[k] as unknown[]).every(nonBlank)); }
export function normalizeThemeProviderOutput(value: unknown): ThemeAnalysis | null { if (validateThemeAnalysis(value)) return value; if (!isRecord(value) || Object.prototype.hasOwnProperty.call(value, 'format') || Object.prototype.hasOwnProperty.call(value, 'seeds') || typeof value.category !== 'string' || !Array.isArray(value.searchSeeds) || typeof value.confidence !== 'number' || !Number.isFinite(value.confidence) || value.confidence < 0 || value.confidence > 1) return null; const normalized = { ...value, format: value.category, seeds: value.searchSeeds, confidence: value.confidence * 100 }; return validateThemeAnalysis(normalized) ? normalized : null; }
const componentKeys = ['themeRelevance','intentMatch','normalizedVolume','titleNaturalness','clickPotential'] as const;
const validComponents = (value: unknown) => isRecord(value) && componentKeys.every(key => score(value[key]));
export function validateWriterRankingOutput(value: unknown, candidates: Array<KeywordCandidate & { normalizedVolume: number }>): value is WriterRankingOutput { if (!isRecord(value) || !Array.isArray(value.keywordScores) || value.keywordScores.length !== candidates.length || (value.naturalSearchLanguageMismatch !== undefined && typeof value.naturalSearchLanguageMismatch !== 'boolean')) return false; const expected = new Map(candidates.map(candidate => [candidate.phrase, candidate.normalizedVolume])); const seen = new Set<string>(); return value.keywordScores.every(entry => { if (!isRecord(entry) || typeof entry.phrase !== 'string' || !expected.has(entry.phrase) || seen.has(entry.phrase) || !validComponents(entry.components)) return false; const components = entry.components as Record<string, unknown>; seen.add(entry.phrase); return components.normalizedVolume === expected.get(entry.phrase); }) && seen.size === expected.size; }
export function validateWriterDraftOutput(value: unknown, profile: PodcastProfile, selectedPhrase: string): value is WriterDraftOutput { if (!isRecord(value) || !Array.isArray(value.titles) || value.titles.length !== 3 || !string(value.description, profile.descriptionMinLength, profile.descriptionMaxLength) || !nonBlank(value.reason) || value.reason.trim().split(/\s+/).length > 20) return false; const roles = ['balanced','search_focused','curiosity']; if (!value.titles.every((title, index) => isRecord(title) && title.role === roles[index] && string(title.title, profile.titleMinLength, profile.titleMaxLength) && title.primaryPhrase === selectedPhrase)) return false; if (value.description.split(selectedPhrase).length - 1 !== 1) return false; return [value.currentTitleComponents, value.recommendedTitleComponents].filter(value => value !== undefined).every(validComponents); }
