import { NextResponse } from 'next/server';
import { isStaff } from '@/lib/trainer/auth';
import { analyzePodcastEpisodeOutcome, createStoredEpisodeAnalysis } from '@/lib/podcast-title/analyzeEpisode';
import { readPodcastProfile, writeEpisodeAnalysisAtomic } from '@/lib/podcast-title/store';
import { validId, type AdminPodcastProfile } from '@/lib/podcast-title/adminApi';
import { validateEpisodeInput } from '@/lib/podcast-title/validation';
export const runtime = 'nodejs'; export const dynamic = 'force-dynamic';
const failureResponses = { timeout: { status: 504, error: 'analysis_timeout' }, aborted: { status: 503, error: 'analysis_aborted' }, unavailable: { status: 502, error: 'provider_unavailable' }, invalid_output: { status: 502, error: 'provider_invalid_output' } } as const;
export async function POST(request: Request) { if (!await isStaff()) return NextResponse.json({ error: 'unauthorized' }, { status: 401 }); let body: unknown; try { body = await request.json(); } catch { return NextResponse.json({ error: 'invalid_json' }, { status: 400 }); } const input = body && typeof body === 'object' ? body as Record<string, unknown> : null; const profileId = typeof input?.profileId === 'string' ? input.profileId : null; if (!validId(profileId) || !validateEpisodeInput(input)) return NextResponse.json({ error: 'invalid_request' }, { status: 400 }); const profile = await readPodcastProfile(profileId) as AdminPodcastProfile | null; if (!profile) return NextResponse.json({ error: 'profile_not_found' }, { status: 404 }); try { const outcome = await analyzePodcastEpisodeOutcome(input, profile); if (outcome.status === 'completed') { const analysis = createStoredEpisodeAnalysis(profile, input, outcome.result, outcome.providerUsage); if (!await writeEpisodeAnalysisAtomic(analysis)) return NextResponse.json({ error: 'storage_unavailable' }, { status: 500 }); return NextResponse.json({ analysis }); } const response = failureResponses[outcome.failure.code]; return NextResponse.json({ error: response.error, stage: outcome.failure.stage, ...(outcome.failure.step ? { step: outcome.failure.step } : {}) }, { status: response.status }); } catch { return NextResponse.json({ error: 'analysis_failed' }, { status: 500 }); } }
